name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: gcr.io/crosvm-infra/crosvm_dev:latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Cargo Dist
      run: cargo install cargo-dist --locked
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo dist build --verbose
